# Generated by Django 4.2.3 on 2023-07-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='customer',
        ),
    ]
