# Generated by Django 4.2.3 on 2023-07-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_document_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id_number',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
