# Generated by Django 4.2.3 on 2023-07-24 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_document_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='option4',
        ),
    ]
