# Generated by Django 4.2.3 on 2023-07-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_quizanswer_remove_quizquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuizResult',
        ),
    ]
