# Generated by Django 4.2.3 on 2023-07-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('certificate', 'Certificate'), ('sales_receipt', 'Sales Receipt'), ('contract', 'Contract'), ('others', 'Others')], max_length=20, null=True),
        ),
    ]
