# Generated by Django 4.2.3 on 2023-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
